// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuPQ9-D1-DDBy0aVWkI3x1bu8Qw-0R9kY',
    appId: '1:567498365278:web:a6b718858dd2de984197cf',
    messagingSenderId: '567498365278',
    projectId: 'gp-project-cb915',
    authDomain: 'gp-project-cb915.firebaseapp.com',
    storageBucket: 'gp-project-cb915.appspot.com',
    measurementId: 'G-VHG8CZEJX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfvNwnkoGoJlG4fq1Lx2qAXqUpDjWG604',
    appId: '1:567498365278:android:bd3c7db97f84bfd54197cf',
    messagingSenderId: '567498365278',
    projectId: 'gp-project-cb915',
    storageBucket: 'gp-project-cb915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgy2hw1NKcmO35xM3hhpXN1neE1iaEz-4',
    appId: '1:567498365278:ios:c2567e47fe5059a44197cf',
    messagingSenderId: '567498365278',
    projectId: 'gp-project-cb915',
    storageBucket: 'gp-project-cb915.appspot.com',
    iosClientId: '567498365278-sv4ru6mq4flnrka20vrhnjflf35kc7b5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sonar',
  );
}
